### ISSUE TITLE
local_zig still tries to download zig

### ISSUE THREAD

**Issue by jeregrine** [ityonemo/zigler#253]
I have zig working locally on my arm m1 mac and I can use/build things with zig proper no problem. 

But when I set `local_zig` to true it still tries to download a source that it won't be able to find and fails. Should local_zig flag mean to skip those steps and just make sure that the zig executable is available? Or am I misinterpreting what it should do.

**Comment by ityonemo** [comment]
thanks for the bug report!  I will try to get to it in the next few weeks.

**Comment by ityonemo** [comment]
@jeregrine do you have an immediate use case for this?  I'm considering punting this to 0.8.0 release (which should come out ~ july), because I'm going to rearchitect how the system assembles the temporary directory

**Comment by jeregrine** [comment]
@ityonemo nope I was just playing around with it. My MAIN usecase is that I'm on the new apple m1 laptops and I could trivially build zig locally I could not use zigler. I DID take a stab at implementing this but yea I think reworking it smart. 

It looks like zig has proper arm builds published now so I could make it work by adding a url to the list https://ziglang.org/download/

**Comment by batok** [comment]
I see above that local_zig makes zigler not download zig.  I have zig installed via asdf, can i use my zig installed via asdf, and if so where on set local_zig = true?

**Comment by ityonemo** [comment]
should be fixed now in d1afc54

**Comment by CharlesOkwuagwu** [comment]
Still a problem here:

```
** (ErlangError) Erlang error: :enoent
    erlang.erl:4430: :erlang.open_port({:spawn_executable, 'c:/Projects/gw/deps/zigler/zig/zig-windows-i386-0.8.1/zig'}, [:use_stdio, :exit_status, :binary, :hide, {:args, ["targets"]}])
```

My local zig copy works, and is installed here: c:/zig/
